# Generated by Django 3.0.6 on 2020-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtask',
            name='last_edited_date',
            field=models.DateField(auto_now=True),
        ),
    ]
