# Generated by Django 3.0.6 on 2020-05-19 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200518_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tasks.ListTask'),
        ),
    ]
