# Generated by Django 3.0.6 on 2020-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200519_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='listtask',
            name='tag',
        ),
        migrations.AddField(
            model_name='listtask',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='tasks.Tag'),
        ),
    ]
